SELECT * FROM customer_behavior limit 5;

--Q1. What is the total revenue generated by male vs. female customers?
-- Impact:-This analysis helps identify the most revenue-generating gender segment, 
-- enabling targeted marketing, optimized inventory planning, improved pricing strategies, 
-- and higher overall profitability.

SELECT * FROM customer_behavior
select gender,sum(purchase_amount) from customer_behavior
group by gender


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT * FROM customer_behavior
select customer_id, purchase_amount 
from customer_behavior 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_behavior)

-- - Q3. Which are the top 5 products with the highest average review rating?
-- Impact:-Products with high Avg rating can be sold att high prices and can be highlighted for ads campagin

SELECT * FROM customer_behavior

SELECT 
   item_purchased,ROUND(AVG(review_rating::numeric), 2) AS "Avg customer rating"
FROM customer_behavior
GROUP BY item_purchased
ORDER BY AVG(review_rating::numeric) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT * FROM customer_behavior

select shipping_type,ROUND(AVG(purchase_amount::numeric), 2) 
from customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
-- Impact:-This analysis evaluates the revenue impact of subscription status, 
-- helping determine whether subscribers contribute higher average and 
-- total revenue, which guides retention and monetization strategies.

SELECT * FROM customer_behavior

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_amount,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_amount DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- impact:-This analysis measures how frequently discounts are applied per product,
-- helping optimize promotional strategies and protect profitability.

SELECT * FROM customer_behavior

select item_purchased,
  ROUND(100.0 * SUM(case 
  when discount_applied='Yes' then 1 else 0 end
  )/COUNT(*),2) as Percentage_discount from customer_behavior
  group by item_purchased
  order by Percentage_discount desc limit 5;

-- -Q7. Segment customers into New, Returning, and Loyal based on their total 
 -- number of previous purchases, and show the count of each segment. 
-- impact:-This analysis segments customers based on purchase history to understand customer
-- maturity levels, enabling targeted retention and loyalty strategies.

SELECT * FROM customer_behavior

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_behavior)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


-- 8.What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT * FROM customer_behavior

select subscription_status,count(customer_id) as Repeat_buyer
from customer_behavior
where previous_purchases>5
group by subscription_status


--Q10. What is the revenue contribution of each age group? 

SELECT * FROM customer_behavior
select age_group,
sum(purchase_amount) as reveune_age
from customer_behavior
group by age_group
order by reveune_age desc;





















